# Assignment 3
## CIS 666, Spring 2021

---

### Bradley Dowling
### CSU ID: 2657649

In [1]:
import numpy as np
from sklearn.svm import SVC
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from mnist import MNIST

In [2]:
clf = make_pipeline(StandardScaler(), SVC(kernel='linear'))
mndata = MNIST('./emnist_data')
mndata.gz = True
mndata.select_emnist('digits')
images, labels = mndata.load_training()

Part 1:
---
Train Linear SVM on 1000 MNIST digits and test against 100

In [3]:
testX = [np.array(image).reshape(1, -1) for image in images[2000:2100]]
clf.fit(images[:1000], labels[:1000])
predicted = [int(clf.predict(x)) for x in testX]
true = list(int(y) for y in labels[2000:2100])
r1 = [x == y for x, y in zip(predicted, true)]

confusion_matrix(true, predicted)

array([[ 8,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  6,  1,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  7,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  0, 10,  0,  0,  0,  0,  0,  0],
       [ 1,  0,  0,  0,  9,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1,  0, 12,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  9,  0,  0,  0],
       [ 0,  0,  0,  0,  1,  0,  0, 14,  0,  1],
       [ 0,  0,  1,  0,  0,  0,  1,  0,  7,  1],
       [ 0,  0,  1,  0,  0,  0,  0,  0,  0,  8]])

Part 2:
---
Train Linear SVM on 10000 MNIST digits and test against 100

In [4]:
testX = [np.array(image).reshape(1, -1) for image in images[20000:20100]]
clf.fit(images[:10000], labels[:10000])
predicted = [int(clf.predict(x)) for x in testX]
true = list(int(y) for y in labels[20000:20100])
r2 = [x == y for x, y in zip(predicted, true)]

confusion_matrix(true, predicted)

array([[12,  0,  0,  0,  1,  0,  0,  0,  0,  0],
       [ 0,  7,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  0, 10,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 10,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 11,  0,  0,  0,  0,  0],
       [ 0,  0,  1,  0,  0, 10,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  6,  0,  0,  0],
       [ 0,  0,  0,  0,  1,  0,  0, 12,  0,  0],
       [ 0,  0,  0,  0,  0,  1,  1,  0,  9,  0],
       [ 0,  0,  0,  0,  1,  0,  0,  0,  0,  6]])

Part 3:
---
Train Linear SVM on 10000 MNIST digits and test against 1000

In [5]:
testX = [np.array(image).reshape(1, -1) for image in images[20000:21000]]
clf.fit(images[:10000], labels[:10000])
predicted = [int(clf.predict(x)) for x in testX]
true = list(int(y) for y in labels[20000:21000])
r3 = [x == y for x, y in zip(predicted, true)]

confusion_matrix(true, predicted)

array([[ 95,   1,   0,   0,   1,   0,   1,   0,   0,   0],
       [  0, 103,   1,   2,   0,   0,   0,   0,   0,   0],
       [  2,   1, 100,   4,   4,   0,   1,   0,   2,   0],
       [  1,   1,   3,  87,   0,   1,   0,   1,   4,   0],
       [  1,   0,   0,   0,  98,   0,   1,   1,   1,   0],
       [  1,   1,   3,   4,   0,  87,   0,   0,   1,   1],
       [  0,   0,   1,   0,   0,   0,  76,   0,   0,   0],
       [  0,   0,   0,   0,   1,   0,   0,  91,   1,   2],
       [  1,   1,   2,   3,   1,   2,   1,   0,  98,   0],
       [  0,   0,   0,   0,   6,   0,   0,   4,   2,  91]])

Part 5:
---
RBF Kernel

In [6]:
rbf = make_pipeline(StandardScaler(), SVC(kernel='rbf'))
testX = [np.array(image).reshape(1, -1) for image in images[20000:21000]]
rbf.fit(images[:10000], labels[:10000])
predicted = [int(rbf.predict(x)) for x in testX]
true = list(int(y) for y in labels[20000:21000])
r5r = [x == y for x, y in zip(predicted, true)]

confusion_matrix(true, predicted)

array([[ 96,   0,   1,   0,   1,   0,   0,   0,   0,   0],
       [  0, 103,   1,   0,   0,   0,   0,   1,   1,   0],
       [  1,   0, 109,   1,   1,   0,   0,   0,   2,   0],
       [  0,   0,   4,  89,   0,   1,   0,   1,   3,   0],
       [  0,   1,   1,   0,  98,   0,   0,   1,   0,   1],
       [  0,   0,   2,   1,   0,  93,   0,   0,   2,   0],
       [  0,   0,   0,   0,   0,   0,  77,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,  92,   0,   3],
       [  0,   0,   3,   1,   0,   3,   1,   0, 100,   1],
       [  0,   0,   1,   0,   1,   0,   0,   1,   1,  99]])

Polynomial Kernel

In [7]:
poly = make_pipeline(StandardScaler(), SVC(kernel='poly'))
testX = [np.array(image).reshape(1, -1) for image in images[20000:21000]]
poly.fit(images[:10000], labels[:10000])
predicted = [int(poly.predict(x)) for x in testX]
true = list(int(y) for y in labels[20000:21000])
r5p = [x == y for x, y in zip(predicted, true)]

confusion_matrix(true, predicted)

array([[ 94,   0,   0,   0,   1,   0,   0,   0,   3,   0],
       [  0, 102,   1,   0,   0,   0,   0,   1,   1,   1],
       [  1,   0, 100,   1,   1,   1,   0,   1,   9,   0],
       [  0,   0,   2,  90,   0,   1,   0,   1,   3,   1],
       [  0,   1,   0,   0,  99,   0,   0,   1,   0,   1],
       [  0,   0,   0,   2,   1,  95,   0,   0,   0,   0],
       [  0,   1,   0,   0,   0,   1,  75,   0,   0,   0],
       [  0,   0,   0,   0,   1,   0,   0,  91,   0,   3],
       [  1,   0,   1,   0,   1,   2,   0,   0, 103,   1],
       [  0,   0,   0,   0,   1,   0,   0,   0,   1, 101]])

Sigmoid Kernel

In [8]:
sigmoid = make_pipeline(StandardScaler(), SVC(kernel='poly'))
testX = [np.array(image).reshape(1, -1) for image in images[20000:21000]]
sigmoid.fit(images[:10000], labels[:10000])
predicted = [int(sigmoid.predict(x)) for x in testX]
true = list(int(y) for y in labels[20000:21000])
r5s = [x == y for x, y in zip(predicted, true)]

confusion_matrix(true, predicted)

array([[ 94,   0,   0,   0,   1,   0,   0,   0,   3,   0],
       [  0, 102,   1,   0,   0,   0,   0,   1,   1,   1],
       [  1,   0, 100,   1,   1,   1,   0,   1,   9,   0],
       [  0,   0,   2,  90,   0,   1,   0,   1,   3,   1],
       [  0,   1,   0,   0,  99,   0,   0,   1,   0,   1],
       [  0,   0,   0,   2,   1,  95,   0,   0,   0,   0],
       [  0,   1,   0,   0,   0,   1,  75,   0,   0,   0],
       [  0,   0,   0,   0,   1,   0,   0,  91,   0,   3],
       [  1,   0,   1,   0,   1,   2,   0,   0, 103,   1],
       [  0,   0,   0,   0,   1,   0,   0,   0,   1, 101]])

Part 6:
---
Create binary images based on threshold 100

In [9]:
threshold = 100
binary_images = []
for image in images[:10000]:
    bimage = []
    for pixel in image:
        if pixel >= threshold:
            bimage.append(255)
        else:
            bimage.append(0)
    binary_images.append(bimage)

In [10]:
testX = [np.array(image).reshape(1, -1) for image in images[20000:21000]]
clf.fit(images[:10000], labels[:10000])
predicted = [int(clf.predict(x)) for x in testX]
true = list(int(y) for y in labels[20000:21000])
r6 = [x == y for x, y in zip(predicted, true)]

confusion_matrix(true, predicted)

array([[ 95,   1,   0,   0,   1,   0,   1,   0,   0,   0],
       [  0, 103,   1,   2,   0,   0,   0,   0,   0,   0],
       [  2,   1, 100,   4,   4,   0,   1,   0,   2,   0],
       [  1,   1,   3,  87,   0,   1,   0,   1,   4,   0],
       [  1,   0,   0,   0,  98,   0,   1,   1,   1,   0],
       [  1,   1,   3,   4,   0,  87,   0,   0,   1,   1],
       [  0,   0,   1,   0,   0,   0,  76,   0,   0,   0],
       [  0,   0,   0,   0,   1,   0,   0,  91,   1,   2],
       [  1,   1,   2,   3,   1,   2,   1,   0,  98,   0],
       [  0,   0,   0,   0,   6,   0,   0,   4,   2,  91]])

Part 7:
---


In [11]:
print("Accuracy")
print(f"Part 1: \t\t\t{sum(r1) / len(r1)}")
print(f"Part 2: \t\t\t{sum(r2) / len(r2)}")
print(f"Part 3: \t\t\t{sum(r3) / len(r3)}")
print(f"Part 5 - RBF: \t\t\t{sum(r5r) / len(r5r)}")
print(f"Part 5 - Polynomial: \t\t{sum(r5p) / len(r5p)}")
print(f"Part 5 - Sigmoid: \t\t{sum(r5s) / len(r5s)}")
print(f"Part 6: \t\t\t{sum(r6) / len(r6)}")

Accuracy
Part 1: 			0.9
Part 2: 			0.93
Part 3: 			0.926
Part 5 - RBF: 			0.956
Part 5 - Polynomial: 		0.95
Part 5 - Sigmoid: 		0.95
Part 6: 			0.926
